name: Node.js CI

on:
  push:
    branches: [ "main" ]
  repository_dispatch:
    branches: [ "main" ]
    types: [update_post]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 18.12.1
    - run: touch .env
    - run: echo "WORDPRESS_API_URL=${{ secrets.WORDPRESS_API_URL }}" >> .env
    - run: echo "GA_CLIENT_EMAIL=${{ secrets.GA_CLIENT_EMAIL }}" >> .env
    - run: echo "GA_PRIVATE_KEY=${{ secrets.GA_PRIVATE_KEY }}" >> .env
    - run: echo "GA_PROPERTY_ID=${{ secrets.GA_PROPERTY_ID }}" >> .env
    - run: echo "NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID }}" >> .env
    - run: cat .env
    - name: yarn install
      run: |
           npm install
           npm run build
    - name: deploy to Firebase Hosting
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

